export class IncomeStatement {
    constructor(
        public date : string,
        public symbol : string,
        public reportedCurrency : string,
        public fillingDate : string,
        public acceptedDate : string,
        public period : string,
        public revenue : number,
        public costOfRevenue : number,
        public grossProfit : number,
        public grossProfitRatio : number,
        public researchAndDevelopmentExpenses : number,
        public generalAndAdministrativeExpenses : number,
        public sellingAndMarketingExpenses : number,
        public otherExpenses : number,
        public operatingExpenses : number,
        public costAndExpenses : number,
        public interestExpense : number,
        public depreciationAndAmortization : number,
        public ebitda : number,
        public ebitdaratio : number,
        public operatingIncome : number,
        public operatingIncomeRatio : number,
        public totalOtherIncomeExpensesNet : number,
        public incomeBeforeTax : number,
        public incomeBeforeTaxRatio : number,
        public incomeTaxExpense : number,
        public netIncome : number,
        public netIncomeRatio : number,
        public eps : number,
        public epsdiluted : number,
        public weightedAverageShsOut : number,
        public weightedAverageShsOutDil : number,
        public link : string,
        public finalLink : string
    ){}
}
